name: mysnaptest
version: '0.1'
summary: Qt Hello World example
description: A simple Qt example
confinement: strict
grade: stable
base: core18

apps:
  mysnaptest:
    command: mysnaptest
    plugs:
      - x11

parts:
  mysnaptest:
    plugin: cmake
    source: src/
    build-packages:
      - qtbase5-dev
    stage-packages:
      # Here for the plugins-- they're not linked in automatically.
      - libqt5gui5
    after: [qt5conf] # A cloud part
