name: hello-world-desktop
version: 0.1
summary: Qt Hello World example
description: A simple Qt example

apps:
  hello-world-desktop:
    command: qt5-launch hello-world-desktop
    plugs:
      - x11

parts:
  hello-world:
    plugin: cmake
    source: src/
    build-packages:
      - qtbase5-dev
    stage-packages:
      # Here for the plugins-- they're not linked in automatically.
      - libqt5gui5
    after: [qt5conf] # A cloud part
